[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stockpilot = "CsiP2ZWy1bM6Ghye85r67kiLC2zkBC7FngYCYGAhEPgK"

[programs.devnet]
stockpilot = "CsiP2ZWy1bM6Ghye85r67kiLC2zkBC7FngYCYGAhEPgK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf"
